---
server:
    install: '1'
    packages: [git]
    timezone: Europe/Warsaw
    locale: pl_PL.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: SeriesReader, ip: 192.168.33.100, memory: '2048', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/web
    servername: Series_reader.local
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt]
xdebug:
    install: '1'
composer:
    install: '1'

